//! Core data types and lifecycle events for the Agent Teams feature.
//!
//! Agent Teams layer a shared task board and a named team roster on top of the
//! existing multi-agent subsystem (`multi_agent_v2`). A team is the spawn
//! subtree rooted at the lead; this module only models the data that the lead
//! and teammates exchange. The board mutation logic lives in `codex-core`.
//!
//! See `docs/rfcs/0001-agent-teams.md`.

use crate::AgentPath;
use crate::ThreadId;
use schemars::JsonSchema;
use serde::Deserialize;
use serde::Serialize;
use std::fmt;
use ts_rs::TS;

/// Stable, team-local identifier for a teammate (e.g. "researcher").
///
/// Distinct from [`AgentPath`], which is structural. The lead assigns these so
/// that teammates can address each other by a predictable name.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema, TS)]
#[serde(transparent)]
pub struct TeammateName(pub String);

/// Opaque identifier for a team. Used in on-disk persistence paths.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema, TS)]
#[serde(transparent)]
pub struct TeamId(pub String);

/// Opaque identifier for a task on the shared board.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema, TS)]
#[serde(transparent)]
pub struct TaskId(pub String);

macro_rules! string_newtype_impls {
    ($ty:ident) => {
        impl $ty {
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl fmt::Display for $ty {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl From<String> for $ty {
            fn from(value: String) -> Self {
                Self(value)
            }
        }

        impl From<&str> for $ty {
            fn from(value: &str) -> Self {
                Self(value.to_string())
            }
        }
    };
}

string_newtype_impls!(TeammateName);
string_newtype_impls!(TeamId);
string_newtype_impls!(TaskId);

/// Lifecycle state of a task on the shared board.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "snake_case")]
pub enum TaskStatus {
    /// Not yet claimed by any teammate.
    Pending,
    /// Claimed and actively being worked on.
    InProgress,
    /// Finished successfully.
    Completed,
    /// Abandoned; will not be worked on.
    Cancelled,
}

impl TaskStatus {
    /// Whether the task has reached a terminal state and will not change again.
    pub fn is_terminal(self) -> bool {
        matches!(self, TaskStatus::Completed | TaskStatus::Cancelled)
    }
}

/// A single unit of work on the shared team board.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(deny_unknown_fields)]
pub struct Task {
    pub id: TaskId,
    /// Short, human-readable summary. Bounded at the tool boundary.
    pub title: String,
    /// Optional longer description. Bounded at the tool boundary.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    pub status: TaskStatus,
    /// `None` means unclaimed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assignee: Option<TeammateName>,
    /// Task is blocked until every dependency is `Completed`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<TaskId>,
    pub created_by: TeammateName,
    pub created_at_ms: u64,
    pub updated_at_ms: u64,
}

impl Task {
    /// Returns the dependencies that are not yet satisfied given the set of
    /// completed task ids. A task is claimable only when this is empty.
    pub fn unmet_dependencies<'a>(
        &'a self,
        is_completed: impl Fn(&TaskId) -> bool + 'a,
    ) -> Vec<&'a TaskId> {
        self.depends_on
            .iter()
            .filter(|dep| !is_completed(dep))
            .collect()
    }
}

/// A teammate registered in the team roster.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(deny_unknown_fields)]
pub struct TeamMember {
    pub name: TeammateName,
    /// Bridges to the existing structural agent addressing.
    pub agent_path: AgentPath,
    pub agent_id: ThreadId,
    /// Existing role name applied to this teammate, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

/// Runtime configuration for a team. Regenerated by the lead as members join or
/// leave; never hand-authored.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(deny_unknown_fields)]
pub struct TeamConfig {
    pub id: TeamId,
    pub name: String,
    pub lead_thread_id: ThreadId,
    #[serde(default)]
    pub members: Vec<TeamMember>,
}

// ---------------------------------------------------------------------------
// Lifecycle events (surfaced through `EventMsg`).
// ---------------------------------------------------------------------------

/// A team was created by the lead.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
pub struct TeamCreatedEvent {
    pub team_id: TeamId,
    pub name: String,
}

/// A teammate joined the team roster.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
pub struct TeamMemberJoinedEvent {
    pub team_id: TeamId,
    pub member: TeamMember,
}

/// A task was added to the board.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
pub struct TaskCreatedEvent {
    pub team_id: TeamId,
    pub task: Task,
}

/// A task changed status and/or assignee.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
pub struct TaskUpdatedEvent {
    pub team_id: TeamId,
    /// The full task after the update, so clients can render the board without a
    /// separate fetch (uniform with `TaskCreatedEvent`).
    pub task: Task,
}

/// A previously blocked task became claimable because its dependencies
/// completed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
pub struct TaskUnblockedEvent {
    pub team_id: TeamId,
    pub task_id: TaskId,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unmet_dependencies_filters_completed() {
        let task = Task {
            id: TaskId::from("t3"),
            title: "ship".to_string(),
            details: None,
            status: TaskStatus::Pending,
            assignee: None,
            depends_on: vec![TaskId::from("t1"), TaskId::from("t2")],
            created_by: TeammateName::from("lead"),
            created_at_ms: 0,
            updated_at_ms: 0,
        };
        let completed = [TaskId::from("t1")];
        let unmet = task.unmet_dependencies(|dep| completed.contains(dep));
        assert_eq!(unmet, vec![&TaskId::from("t2")]);
    }

    #[test]
    fn task_status_terminal() {
        assert!(TaskStatus::Completed.is_terminal());
        assert!(TaskStatus::Cancelled.is_terminal());
        assert!(!TaskStatus::Pending.is_terminal());
        assert!(!TaskStatus::InProgress.is_terminal());
    }

    #[test]
    fn newtype_roundtrips_transparently() {
        let id = TaskId::from("abc");
        let json = serde_json::to_string(&id).expect("serialize");
        assert_eq!(json, "\"abc\"");
        let back: TaskId = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, id);
        assert_eq!(id.as_str(), "abc");
        assert_eq!(id.to_string(), "abc");
    }
}
